### ISSUE TITLE
"Choose Theme" and "Font Size" are not replicating.

### ISSUE THREAD

**Issue by POP1912** [prince776/discode#8]
The default values for "Font Size" is 18 and for "Choose Theme" is monokai for Screen 1. If I change these values before sharing my ID for Screen2, the Screen 2 is having Default values only. Also the changes I change in Screen 1 are not replicating in Screen2 for these tabs.

Screen1:
![image](https://user-images.githubusercontent.com/48610563/121395726-597fcd00-c970-11eb-887b-8802ca9e5133.png)

Screen 2:
![image](https://user-images.githubusercontent.com/48610563/121395972-8af89880-c970-11eb-8377-41ba61d3b611.png)

As you can see from the both images, only the "Choose Language" tab is reflecting.

**Comment by prince776** [comment]
This is intentional, I do not want to communicate change in theme/font to other people in the room as members should be able to have these things different without actually affecting the room.

Body,input, outpout, lang etc are all part of the room whereas theme, font size, history as part of user settings, which are stored in localStorage as there's no signup/login which is again intentional, for ease of use. 

Now there's one bug:
- I open a  room in one tab
- I open another(or same) room in another tab
- now changing the theme/font size won't affect the other tab, it'd only take action after a refresh (as it loads it from localStorage)
Now this is very minute and doesn't necessarily need a fix imo.
